import { UserRole, UserStatus } from "@prisma/client";

export { UserRole, UserStatus };

//JWT Token Types
export enum TokenType {
  ACCESS = "access",
  REFRESH = "refresh",
}

//Authentication Error Codes
export const AuthErrorCode = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  ACCOUNT_PENDING: "ACCOUNT_PENDING",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
} as const;

//Password & Token Limits
export const AuthLimits = {
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,

  PASSWORD_RESET_TOKEN_BYTES: 48,
  EMAIL_VERIFICATION_TOKEN_BYTES: 48,
} as const;